### PR TITLE
Many fixes, timeouts, errors. 

### PR DESCRIPTION
**Pull request by chepo92**
Enabled error handling:  Marlin reports "Error" (capital E)
set cancelPrint= true flag works and stop sending (tested with heating fault error)
Added position parser
Fixes M190 M109 timeouts

### CODE REVIEW

**Comment by GMagician** [comment]
Even it it works I don't like resetting timeout timer when you receive temp or echo...
timeout timer should detect "timeout" in sent command it's not a generic receive timeout

It's ok you have G28 issue and is fixed by this (but I want to see if there is a different solution) but I'm wondering why I don't see any "printer sent buys" message after temperature commands? Autotemp and busy are sent every 2 seconds so I should see both of them before timeout (really I should see just 1 autotemp before timeout and not 3)
What is not working as expected here?

**Comment by chepo92** [comment]
> Even it it works I don't like resetting timeout timer when you receive temp or echo...
> timeout timer should detect "timeout" in sent command it's not a generic receive timeout
> 

temp should reset timer only if there is a pending response. echo:busy should always reset (as the printer is busy with the las command sent) and is blocked. echo:cold means you should pause sending commands because they will be ignored (resetting is basic a way of pausing) 


> It's ok you have G28 issue and is fixed by this (but I want to see if there is a different solution) but I'm wondering why I don't see any "printer sent buys" message after temperature commands? Autotemp and busy are sent every 2 seconds so I should see both of them before timeout (really I should see just 1 autotemp before timeout and not 3)
> What is not working as expected here?

**Comment by GMagician** [comment]
@chepo92 can you check in your firmware if BUSY_WHILE_HEATING is enabled or not?

**Comment by GMagician** [comment]
@chepo92 I checked my 2.0 marlin and it echo busy even when homing and even 1.1.x does it

I agree with you when timer should be reset but this is not what your code does.
Temp response already reset timeout when required by M105 because of answer start with 'ok' (but we miss it parsing and thats not good)
when `parseTemperatures(serialResponse)` no reset timer is needed then because it is valid  only for autotemp

**Comment by chepo92** [comment]
> 
> 
> @chepo92 can you check in your firmware if BUSY_WHILE_HEATING is enabled or not?

Yes it is enabled

> when `parseTemperatures(serialResponse)` no reset timer is needed then because it is valid only for autotemp

But it needs more time until you receive the echo:busy, if it can parse temps but was waiting for the ok after the M190 should just give it more time. 

Do you know how often it reports echo:busy when processing a command? that should be the keep Alive parameter as I think is slower than temp report.

**Comment by GMagician** [comment]
@chepo92 

> Do you know how often it reports echo:busy when processing a command? that should be the keep Alive parameter as I think is slower than temp report.

Yes 2 seconds that's why I set timeout to 2.5

**Comment by GMagician** [comment]
Too late, marge to mastger has been done. I added some of these in my PR #64

**Pull request closed without merging**
