### PR TITLE
added MDNS.update() 

### PR DESCRIPTION
**Pull request by chepo92**

### CODE REVIEW

**Comment by GMagician** [comment]
I moved mdsn.update so it's called only when mDNSInit as been called (after printer has been detected) maybe this can help with telnet?

Other question in html response you added volume and print time are these really needed? We will never be able to fill these values and I think they are not mandatory. Can you check please?

**Comment by GMagician** [comment]
Sorry to ask but please be patient. You added 2 include without them do you have some warning/error/issue ?
Usually I try not to add unused things.

**Comment by chepo92** [comment]
adding mdsn.update made it work with cura (it takes some time to discover the service)
I agree better to mdsn.update after printer is detected

**Comment by chepo92** [comment]
> 
> 
> Sorry to ask but please be patient. You added 2 include without them do you have some warning/error/issue ?
> Usually I try not to add unused things.

You mean ESP8266WiFi.h and ESPAsyncTCP.h? I think they are needed for everything (other libraries) to work correctly (and related to mDNS issue), at least for me, otherwise it will use whatever Wifi library you have installed.

**Comment by chepo92** [comment]
> Other question in html response you added volume and print time are these really needed? We will never be able to fill these values and I think they are not mandatory. Can you check please?

I want to implement most of octoprint API capabilities so i started from api documentation (fast forwarding without much questioning if it can be implemented), and yes we can fill them, for example Cura sends this information in commented gcode, so we can parse it. Not critical but would be nice

**Pull request merged**
